"EARTHENGINE_TOKEN" = "1//0g3GryZkbcaQ3CgYIARAAGBASNwF-L9IrqaAYUarYrZ85QndvJqfefkMgSyKnkEGg5jeJM0txFwT1plHuLvWhdpI9tMxrvLqW1es"

[gcp_service_account]
type = "service_account"
project_id = "ee-test-project-426205"
private_key_id = "c5f919ec95a68ad3b23b40f7cdc5400323472db9"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEuQIBADANBgkqhkiG9w0BAQEFAASCBKMwggSfAgEAAoIBAQDR9Bzfr56ePuVa
EvRVs8W2NFJXRUGm3D30EEVV/WIo5K8moDECtvV1g/5bgmWepmVRaL0PXZSNw+iy
LzUHEv9BIgKIpYq/SbS8PM9v1Liw3VRcKC9lAc5bBUxMw6dsTfluaak5nS+/eqJ3
ooVQHkcsb84qqI5QRX4xiPQNcus/iOXqnMXbpcw+MZkNfmAtBz6lZpNJQW/GPCpE
8Mb1Li0lQGf+U1NQ9TypVEs+YQjdlKihx60Ml3o+L6VCSBgLnp7mCDigvR7Oxd/o
NASDWphXsFa30hkcfYxwNtL0ms4gQb/KK3MvzxV/XZ0CMqzvVeBnjh0JqRCPW0RX
Suj3YuPrAgMBAAECgf49qo5mdxxxZG2SY2eT3b2s9tp8v7je0NZegkte5Pl7WxJ+
SjHKKVPGVkEBCc4j7IMuAbkdvMYuRwdKwQgwh5qpFOy+BbpEtjgWlYkBiEWqX08c
rshh2IdQjH8ELu7WzMpCQTeZYC+KsKzaV2s9ScTtcTV4HYFwuhaQ4ByDBhx6E3T7
a/SmgVGXrikX7HGMtBYBmZGgtm6YRpegZW6BWANCsJ/wWWG1Uc88eZf87mKEVAcv
u3aXCl7IFUsG8jcOO+aluyy9IAmfOG4W7AXVx4ldCheUUcE6LUvEBVs5alAaa5H3
PHvz0Nl0vUc1Y7K9B6FzXLmktlXxi3dx0WGImQKBgQD7OidA01oVvTTjrUccWBcR
omgcrs6TSem2tH8GWFkE+GpAoZ91x/dFx6tlyB4Ji/JYwdX6+rmA53qHDlnB6bx+
RnEMAZoZfDp6+iGw/Aq47jAIURIJTeFEKUtz/JJFamgUNCm70r39eEaFySoAimKZ
/DKPSCb/9zkYcx05fDLYXwKBgQDV8TmKbbKsagZtj/DmKykDC9gMclt9dMqAkUCT
zD0dratsSOykIDA6+kZk+OzuJVhUUyQ8LMPEry/Yszts19iGG7LR/il23Bl+pLeS
6pwO6IjLt3EdYqhuftQ4qPp9wpdiKAMzoPJ01J4JRd7qbt1h+XIKuaeXsOkGEmsD
bFvP9QKBgEuyiw9SX6t7Nkt/85RLyq+qktpJpb7ln4FIw5mC11fTDhjpWiXgGdax
wihJ8xsHSv+JcFNOZsS7esTlAxCVwBEAYqGufeM99lUFt08fso9kXZ6z5s5c5Apo
su6A5QX7eN7VlNmeN1b/fahkI77D88/YGNfpcq7frBl83gprLNrbAoGAW4xZ3w6K
ApVsIr4Ri6y0ZAVRciINXGX5sYJ2a8hd7rE+RZv/B0xu1w35yYNrf4yje5IIU2ek
bim5A7XOnAjRMrHvl0R3YdFVZ4f8tfWGyipfPy1EThrFkGLdVVGZvu7h8LLGi/U3
Sx8gcT9g4FiIi0A+uLAxMwwU6vA+srxPnXECgYBfkwFoUmJEL+T2v54lBNBf371q
Dv9/wJ8ITX2k4NEchPv693FA1IZwq+xM4/KSBs92pBViGhgsCOGx4Vz7Ix/NgkWJ
WAkWWcQufk3r/XLuPHQQTA/8Lm0nBFOLMVbjUrHK3GBbXOo090KEojP+4pzjEgJP
jdBDHR82jeFPNgUFRg==
-----END PRIVATE KEY-----"""
client_email = "earth-engine@ee-test-project-426205.iam.gserviceaccount.com"
client_id = "103506848680580707533"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/earth-engine@ee-test-project-426205.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
